AllCops:
  NewCops: enable
  Exclude:
    - 'Gemfile'
    - 'bin/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

# STYLE
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/LambdaCall:
  Enabled: false
Style/SignalException:
  Enabled: false

# LAYOUT
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# METRICS
Metrics/MethodLength:
  Max: 15
